# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d43ea1a8f8e5e7cc55165995cf3a1bb5283c21322d2f0c2457bade20905eb0d8ffdbe7094a430cdd58c8e928651749b55a9d5c18ffc7bb6c5164d7225913c8

test:
  secret_key_base: 3e2df7269171c1ab68129713be318084127de1fc8eefee1a99b4db4945a686e2a8a5de2fc987faf244e0ccdd4ada5ef88f86d4c908a797ebe95f4daae67056c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
